import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wash Me Car Wash Longview | The Only Handwash Tunnel Around!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Link href="/" className=" bg-[#1b3e63] z-50 fixed mb-4 w-full flex justify-center items-center underline text-white capitalize">We are now offering MEMBERSHIPS!!!</Link>
      
    <Navbar />

      {children}
      </body>
    </html>
  );
}
